# 查找所有 .lib 文件
function(find_all_libs dir output_var)
    file(GLOB_RECURSE libs "${dir}/*.lib")
    set(libs_normalized "")
    foreach(lib IN LISTS libs)
        string(REPLACE "\\" "/" lib_normalized "${lib}")
        list(APPEND libs_normalized "${lib_normalized}")
    endforeach()
    set(${output_var} ${libs_normalized} PARENT_SCOPE)
endfunction()

# 查找所有 .exe 文件
function(find_all_exes dir output_var)
    file(GLOB_RECURSE exes "${dir}/*.exe")
    set(exes_normalized "")
    foreach(exe IN LISTS exes)
        string(REPLACE "\\" "/" exe_normalized "${exe}")
        list(APPEND exes_normalized "${exe_normalized}")
    endforeach()
    set(${output_var} ${exes_normalized} PARENT_SCOPE)
endfunction()

# 查找所有 .dll 文件
function(find_all_dlls dir output_var)
    file(GLOB_RECURSE dlls "${dir}/*.dll")
    set(dlls_normalized "")
    foreach(dll IN LISTS dlls)
        string(REPLACE "\\" "/" dll_normalized "${dll}")
        list(APPEND dlls_normalized "${dll_normalized}")
    endforeach()
    set(${output_var} ${dlls_normalized} PARENT_SCOPE)
endfunction()

# 查找所有源文件和头文件，并归一化路径
function(find_sources_and_headers result_var)
    set(sources_and_headers "")
    foreach(path IN LISTS ARGN)
        file(GLOB_RECURSE headers "${path}/*.h" "${path}/*.hpp")
        file(GLOB_RECURSE sources "${path}/*.cpp")
        foreach(f IN LISTS headers sources)
            string(REPLACE "\\" "/" f_normalized "${f}")
            list(APPEND sources_and_headers "${f_normalized}")
        endforeach()
    endforeach()
    set(${result_var} ${sources_and_headers} PARENT_SCOPE)
endfunction()

# 查找所有 .cu、.cuh、.h、.hpp 文件，并归一化路径
function(find_cu_and_headers result_var)
    set(sources_and_headers "")
    foreach(path IN LISTS ARGN)
        file(GLOB_RECURSE headers "${path}/*.h" "${path}/*.hpp" "${path}/*.cuh")
        file(GLOB_RECURSE sources "${path}/*.cu")
        foreach(f IN LISTS headers sources)
            string(REPLACE "\\" "/" f_normalized "${f}")
            list(APPEND sources_and_headers "${f_normalized}")
        endforeach()
    endforeach()
    set(${result_var} ${sources_and_headers} PARENT_SCOPE)
endfunction()

# 分组查找所有源文件和头文件，并归一化路径
function(group_sources_and_headers group_name)
    set(SOURCESFILES "")
    set(HEADERSFILES "")
    foreach(path IN LISTS ARGN)
        file(GLOB_RECURSE headers "${path}/*.h")
        file(GLOB_RECURSE sources "${path}/*.cpp")
        foreach(h IN LISTS headers)
            string(REPLACE "\\" "/" h_normalized "${h}")
            list(APPEND HEADERSFILES "${h_normalized}")
        endforeach()
        foreach(s IN LISTS sources)
            string(REPLACE "\\" "/" s_normalized "${s}")
            list(APPEND SOURCESFILES "${s_normalized}")
        endforeach()
    endforeach()
    source_group("${group_name}/include" FILES ${HEADERSFILES})
    source_group("${group_name}/src" FILES ${SOURCESFILES})
endfunction()

# 分组查找所有接口源文件和头文件，并归一化路径
function(group_interface_sources_and_headers)
    set(SOURCESFILES "")
    set(HEADERSFILES "")
    foreach(path IN LISTS ARGN)
        file(GLOB_RECURSE headers "${path}/*.h")
        file(GLOB_RECURSE sources "${path}/*.cpp")
        foreach(h IN LISTS headers)
            string(REPLACE "\\" "/" h_normalized "${h}")
            list(APPEND HEADERSFILES "${h_normalized}")
        endforeach()
        foreach(s IN LISTS sources)
            string(REPLACE "\\" "/" s_normalized "${s}")
            list(APPEND SOURCESFILES "${s_normalized}")
        endforeach()
    endforeach()
    source_group("Header Files" FILES ${HEADERSFILES})
    source_group("Source Files" FILES ${SOURCESFILES})
endfunction()

# Utility function to check if a specified path exists in a specified system environment variable
function(check_path_in_system_env_var env_var_name search_path result_var)
    message("Check if the system environment variable ${env_var_name} contains ${search_path}" )
    string(TOUPPER "${env_var_name}" env_var_name_upper)
    if (DEFINED ENV{${env_var_name_upper}})
        # Replace backslashes with forward slashes in the environment variable value and search path
        string(REPLACE "\\" "/" env_var_value "$ENV{${env_var_name_upper}}")
        string(REPLACE "\\" "/" search_path_normalized "${search_path}")
        
        string(FIND "${env_var_value}" "${search_path_normalized}" path_index)
        if (path_index GREATER -1)
            set(${result_var} TRUE PARENT_SCOPE)
            message("The system environment variable ${env_var_name} contains ${search_path}" )
        else()
            set(${result_var} FALSE PARENT_SCOPE)
            Message ("The system environment variable ${env_var_name} does not contain ${search_path}")
        endif()
    else()
        set(${result_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

